language: generic
sudo: required
services:
    - docker

before_install:
    - docker build -t vinibotto/docker-react -f Dockerfile.dev .

script:
    - docker run vinibottto/docker-react npm run test -- --coverage